@extends('layouts.ministry')

@section('content')
  @include('partials.hero')
  @include('partials.about')
  @include('partials.daily-push')
  @include('partials.podcast')
  @include('partials.elevation-prayer-spotlight')
  @include('partials.events')
  @include('partials.hunger-cta')
  @include('partials.inspire')
  @include('partials.upcoming-events')
  @include('partials.book-banner')
  @include('partials.video-modal')
@endsection
